<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

Source: MicroMaster DataScience, UC San Diego, https://www.edx.org/es/micromasters/data-science 


### Getting started with ndarray

In [1]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [3]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [4]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


### Rank 2 ndarray


In [5]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


### Multidimensional Arrays

In [6]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [7]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [8]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [9]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [10]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.65472757 0.25021097]
 [0.91974391 0.10119738]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Slice indexing:
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.
</p>

In [12]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [13]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.

In [14]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

Before: 12
After: 1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both integer indexing & slice indexing
</p>

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [15]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [16]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [17]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [19]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [20]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [21]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [22]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [23]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [24]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Array Indexing for changing elements:
</p>

In [25]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [26]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [27]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [28]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [29]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


### Datatypes and Array Operations

In [30]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int32


In [31]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [32]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [33]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [34]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [35]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [36]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [37]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [38]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [39]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [40]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [41]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


### Basic Statistical Operations

In [42]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -6.88427234   2.20316734   8.95767112  15.78986359  16.69581889]
 [-12.83162784  -7.41692511   0.49079903   0.09170942   9.79899758]]


In [43]:
# compute the mean for all elements
print(arr.mean())

2.6895201684604806


In [44]:
# compute the means by row
print(arr.mean(axis = 1))

[ 7.35244972 -1.97340938]


In [45]:
# compute the means by column
print(arr.mean(axis = 0))

[-9.85795009 -2.60687888  4.72423507  7.9407865  13.24740824]


In [46]:
# sum all the elements
print(arr.sum())

26.895201684604807


In [47]:
# compute the medians
print(np.median(arr, axis = 1))

[8.95767112 0.09170942]


In [48]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[-1.18091905 -1.90254201 -0.69869987 -0.73660571 -0.62596915 -1.66787285
  0.76085806  3.18349891 -1.27081041 -0.86877161]


In [49]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.90254201 -1.66787285 -1.27081041 -1.18091905 -0.86877161 -0.73660571
 -0.69869987 -0.62596915  0.76085806  3.18349891]

[-1.18091905 -1.90254201 -0.69869987 -0.73660571 -0.62596915 -1.66787285
  0.76085806  3.18349891 -1.27081041 -0.86877161]


In [50]:
# inplace sorting
unsorted.sort() 

print(unsorted)

[-1.90254201 -1.66787285 -1.27081041 -1.18091905 -0.86877161 -0.73660571
 -0.69869987 -0.62596915  0.76085806  3.18349891]


In [51]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


In [52]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [53]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [54]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [55]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [56]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


### Broadcasting

In [57]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [59]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [60]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [61]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [62]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [65]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


### Additional Common ndarray Operations


In [67]:
# determine the dot product of two matrices
x2d = np.array([[2,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[6 6]
 [4 4]]

[[6 6]
 [4 4]]


In [68]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [69]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[27 18]

[27 18]


In [70]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [71]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [72]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


In [73]:
# random array
x = np.random.randn(8)
x

array([ 1.16799881,  1.82796544, -1.05616575, -0.07605768,  0.82284998,
        1.073617  ,  2.43468587, -0.28976303])

In [74]:
# another random array
y = np.random.randn(8)
y

array([ 0.30650822,  0.24431188, -2.07513558,  1.45236988,  1.08458875,
        0.07699869,  0.721265  , -0.40001523])

In [75]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 1.16799881,  1.82796544, -1.05616575,  1.45236988,  1.08458875,
        1.073617  ,  2.43468587, -0.28976303])

In [76]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [77]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

In [79]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [80]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [81]:
mat = np.random.rand(5,5)
mat

array([[0.51998426, 0.40114279, 0.43225627, 0.63079164, 0.02936088],
       [0.15280353, 0.06349937, 0.21318293, 0.20920611, 0.4632987 ],
       [0.80084644, 0.3938607 , 0.16886071, 0.3281112 , 0.05856609],
       [0.55756824, 0.02878856, 0.13856989, 0.48048674, 0.12623906],
       [0.44736545, 0.88729232, 0.56011429, 0.63326313, 0.30130058]])

In [82]:
np.where( mat > 0.5, 1000, -1)

array([[1000,   -1,   -1, 1000,   -1],
       [  -1,   -1,   -1,   -1,   -1],
       [1000,   -1,   -1,   -1,   -1],
       [1000,   -1,   -1,   -1,   -1],
       [  -1, 1000, 1000, 1000,   -1]])

In [83]:
arr_bools = np.array([ True, False, True, True, False ])

In [84]:
arr_bools.any()

True

In [85]:
arr_bools.all()

False

In [86]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-3.47818621 -0.66429811 -1.91526683 -1.0176577   0.86721711]


In [87]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[15 18 18  2]


In [88]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([ 2, 15, 18, 18])

In [89]:
np.random.uniform(size=4) #uniform distribution

array([0.98808639, 0.60463071, 0.22274439, 0.5942831 ])

In [90]:
np.random.normal(size=4) #normal distribution

array([ 0.76920511, -1.30936838,  1.0917508 ,  1.85713226])

In [91]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[43 45]
 [35 48]]

[[21 11]
 [35 25]]


In [92]:
np.vstack((K,M))

array([[43, 45],
       [35, 48],
       [21, 11],
       [35, 25]])

In [93]:
np.hstack((K,M))

array([[43, 45, 21, 11],
       [35, 48, 35, 25]])

In [94]:
np.concatenate([K, M], axis = 0)

array([[43, 45],
       [35, 48],
       [21, 11],
       [35, 25]])

In [95]:
np.concatenate([K, M.T], axis = 1)

array([[43, 45, 21, 35],
       [35, 48, 11, 25]])